workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      groups:
        - firebase_credentials
      vars:
        GRADLE_USER_HOME: ~/.gradle
        GOOGLE_APPLICATION_CREDENTIALS: $FIREBASE_SERVICE_ACCOUNT
    scripts:
      - name: Build Android App
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease 
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      firebase:
        android:
          app_id: 1:472921504670:android:c0d1d8c1dbe17499a7748f
          artifact_type: 'apk'
          groups: 
            - testers
      email:
        recipients:
          - amr.elskaan@amwal-pay.com
        notify:
          success: true
          failure: true
