workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        GRADLE_USER_HOME: ~/.gradle
        APP_CENTER_TOKEN: $APP_CENTER_TOKEN # Set this in Codemagic UI
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD # Set this in Codemagic UI
        KEY_ALIAS: amwal_key # The alias we used when creating the keystore
        KEY_PASSWORD: $KEY_PASSWORD # Set this in Codemagic UI
    scripts:
      - name: Set up Java
        script: |
          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes openjdk-11-jdk
      - name: Set up Node.js
        script: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: Install AppCenter CLI
        script: |
          npm install -g appcenter-cli@latest
      - name: Decode Keystore
        script: |
          echo $KEYSTORE_BASE64 | base64 --decode > keystore.jks
          echo "Keystore decoded successfully"
          ls -la keystore.jks
      - name: Build Android App
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace \
            -PKEYSTORE_PASSWORD=$KEYSTORE_PASSWORD \
            -PKEY_ALIAS=$KEY_ALIAS \
            -PKEY_PASSWORD=$KEY_PASSWORD
      - name: Verify APK exists
        script: |
          if [ ! -f "app/build/outputs/apk/release/app-release.apk" ]; then
            echo "APK file not found!"
            ls -la app/build/outputs/apk/release/
            exit 1
          fi
      - name: Upload to AppCenter
        script: |
          APK_PATH="app/build/outputs/apk/release/app-release.apk"
          if [ -f "$APK_PATH" ]; then
            appcenter distribute release \
              --group qc \
              --file "$APK_PATH" \
              --app Amwal-Pay/Amwal-Native-SDK \
              --token "${APP_CENTER_TOKEN}" \
              --quiet
          else
            echo "Error: APK file not found at $APK_PATH"
            exit 1
          fi
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - amr.elskaan@amwal-pay.com
        notify:
          success: true
          failure: true 