workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        GRADLE_USER_HOME: ~/.gradle
        FIREBASE_TOKEN: $FIREBASE_TOKEN # Set this in Codemagic UI
    scripts:
      - name: Build Android App
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease 
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - amr.elskaan@amwal-pay.com
        notify:
          success: true
          failure: true
      scripts:
        - name: Upload to Firebase App Distribution
          script: |
            APK_PATH=$(find $CM_BUILD_DIR/app/build/outputs/apk/release -name "*.apk" | head -1)
            if [ -f "$APK_PATH" ]; then
              firebase appdistribution:distribute "$APK_PATH" \
                --app 1:472921504670:android:c0d1d8c1dbe17499a7748f \
                --token "${FIREBASE_TOKEN}" \
                --groups "testers"
            else
              echo "Error: APK file not found at $APK_PATH"
              exit 1
            fi 