workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        GRADLE_USER_HOME: ~/.gradle
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS # Set this in Codemagic UI
    scripts:
      - name: Build Android App
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease 
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      firebase:
        # use this line to authenticate via service account
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        
        # or this line to authenticate via token:
        # firebase_token: $FIREBASE_TOKEN
      
        android:
          # Add your Android app id retrieved from Firebase console
          app_id: 1:472921504670:android:c0d1d8c1dbe17499a7748f
          
          # Add one or more groups that you wish to distribute your Android application to.
          # You can create groups in the Firebase console
          groups: 
            - testers
            - ...
    
      email:
        recipients:
          - amr.elskaan@amwal-pay.com
        notify:
          success: true
          failure: true
