workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        GRADLE_USER_HOME: ~/.gradle
        APP_CENTER_TOKEN: $APP_CENTER_TOKEN # Set this in Codemagic UI
    scripts:
      - name: Install AppCenter CLI
        script: |
          npm install -g appcenter-cli@latest
      - name: Build Android App
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease 
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - amr.elskaan@amwal-pay.com
        notify:
          success: true
          failure: true
      scripts:
        - name: Upload to AppCenter
          script: |
            APK_PATH=$(find $CM_BUILD_DIR/app/build/outputs/apk/release -name "*.apk" | head -1)
            if [ -f "$APK_PATH" ]; then
              appcenter distribute release \
                --group qc \
                --file "$APK_PATH" \
                --app Amwal-Pay/Amwal-Native-SDK \
                --token "${APP_CENTER_TOKEN}" \
                --quiet
            else
              echo "Error: APK file not found at $APK_PATH"
              exit 1
            fi 